spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blogdb
    name: sa
    password: 123456

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect